name: 🎉 Release Binary

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*'  # 只匹配版本号格式的tag，如 v1.0.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: 1.21.x
      
      - name: "Determine release type"
        id: release-type
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=Dev Build $(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi
      
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        with: 
          args: "release --clean"
          version: latest
          workdir: .
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_CURRENT_TAG: "${{ steps.release-type.outputs.release_name }}"
          SLACK_WEBHOOK: "${{ secrets.RELEASE_SLACK_WEBHOOK }}"
          DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"